resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:jigsheth57/concourse-spring-music.git
    branch: master
    private_key: {{git_private_key}}

- name: version
  type: semver
  source:
    bucket: ci-spring-music-artifacts
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: music-release
  type: s3
  source:
    bucket: ci-spring-music-artifacts
    regexp: spring-music-(.*).war
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml
